public enum RunningModeEnum
{
	UNDEFINED = -1,
	EXIT,
	CALIBRATION,
	CALIBRATION_NOISE,
	CALIBRATION_CHESSBOARD,
	CALIBRATION_TARGET,
	CALIBRATION_AUTO_GAIN,
	CALIBRATION_WHITE_BALANCE,
	CALIBRATION_CONTRAST,
	CALIBRATION_MAKE_TARGET,
	CALIBRATION_BALL,
	CALIBRATION_ANALYSIS,
	PROCESS,
	PROCESS_TRACKING,
	STRESS_TESTS,
	SAVE_SESSION,
	DIAGNOSTIC
}
