using System.ComponentModel;

public enum HikrobotParameter
{
	[Description("AcquisitionFrameRate")]
	AcquisitionFrameRate,
	[Description("AcquisitionFrameRateEnable")]
	AcquisitionFrameRateEnable,
	[Description("AcquisitionMode")]
	AcquisitionMode,
	[Description("ADCBitDepth")]
	ADCBitDepth,
	[Description("AutoGainLowerLimit")]
	AutoGainLowerLimit,
	[Description("AutoGainUpperLimit")]
	AutoGainUpperLimit,
	[Description("BalanceRatioSelector")]
	BalanceRatioSelector,
	[Description("BalanceWhiteAuto")]
	BalanceWhiteAuto,
	[Description("BinningVertical")]
	BinningVertical,
	[Description("BinningHorizontal")]
	BinningHorizontal,
	[Description("DeviceReset")]
	DeviceReset,
	[Description("DeviceTemperature")]
	DeviceTemperature,
	[Description("DigitalShift")]
	DigitalShift,
	[Description("DigitalShiftEnable")]
	DigitalShiftEnable,
	[Description("ExposureAuto")]
	ExposureAuto,
	[Description("ExposureMode")]
	ExposureMode,
	[Description("ExposureTime")]
	ExposureTime,
	[Description("Gamma")]
	Gamma,
	[Description("GammaEnable")]
	GammaEnable,
	[Description("Gain")]
	Gain,
	[Description("GainAuto")]
	GainAuto,
	[Description("GainMode")]
	GainMode,
	[Description("Height")]
	Height,
	[Description("LineSelector")]
	LineSelector,
	[Description("LineMode")]
	LineMode,
	[Description("OffsetY")]
	OffsetY,
	[Description("OffsetX")]
	OffsetX,
	[Description("PayloadSize")]
	PayloadSize,
	[Description("PixelFormat")]
	PixelFormat,
	[Description("ResultingFrameRate")]
	ResultingFrameRate,
	[Description("StrobeEnable")]
	StrobeEnable,
	[Description("StrobeLineDuration")]
	StrobeLineDuration,
	[Description("TriggerMode")]
	TriggerMode,
	[Description("TriggerSource")]
	TriggerSource,
	[Description("TriggerCacheEnable")]
	TriggerCacheEnable,
	[Description("TriggerSoftware")]
	TriggerSoftware,
	[Description("Width")]
	Width,
	[Description("DeviceLinkCurrentThroughput")]
	DeviceLinkCurrentThroughput,
	[Description("USBSpeedMode")]
	USBSpeedMode,
	[Description("U3VCurrentSpeed")]
	U3VCurrentSpeed,
	[Description("DeviceFirmwareVersion")]
	DeviceFirmwareVersion,
	[Description("DeviceVersion")]
	DeviceVersion
}
